name=OtamaticClient
version=0.1.0
author=Timothy Franceschi
maintainer=Timothy Franceschi <timothy@franceschi.es>
sentence=Automatic Remote OTA Client for ESP32.
paragraph=This library allows you to perform managed OTA updates on ESP32 devices through the Otamatic platform.
category=Communication
url=https://github.com/TimothyFran/OtamaticClient
architectures=esp32
includes=OtamaticClient.h
depends=Update